### PR TITLE
Add Le Wagon

### PR DESCRIPTION
**Pull request by cimm**
Not a Ruby shop but they sure do Ruby!

### CODE REVIEW

**Comment by toch** [comment]
Shouldn't we dedicate a category for this kind of company?

**Comment by cimm** [comment]
Was thinking the same thing, what if we add a category column to the CSV? Do think it would be useful to have them on the list but it's not a shop...

**Comment by toch** [comment]
Well a column would be a good idea. We can then make the difference between an agency, a product company, or a bootcamp. Do you see other kind of rubyshops?

**Comment by cimm** [comment]
Maybe call it "training" instead of "bootcamp", it's more generic, isn't it? Take Syntra for example, do they consider themselves a bootcamp?

**Comment by toch** [comment]
You're right. Training is better. I don't even know Syntra. What do they do?

**Comment by toch** [comment]
Could you add the column please in your PR and at least the value for LeWagon?

**Comment by cimm** [comment]
Syntra is a network of training centers in Flanders, think they are funded by the Flemish government. They give evening courses, professional trainings for people looking for a job, etc. Will add the column.

**Comment by cimm** [comment]
@toch Added a category column and updated the ones I knew of the top of my head.

**Comment by toch** [comment]
:tada:

**Pull request merged**
