### PR TITLE
Add Digiti to the list

### PR DESCRIPTION
**Pull request by bertgoossens**

### CODE REVIEW

**Comment by toch** [comment]
Hi @bertgoossens and thanks!

**Comment by toch** [comment]
@bertgoossens after having browsed your website, it wasn't clear if you do ruby or not (I should have checked before merging). Could you confirm it? Thanks!

**Comment by Reprazent** [comment]
@toch Don't know if this counts, but [this](http://www.digiti.be/ruby-developer#rd-form) might be an indication?

**Comment by bertgoossens** [comment]
It is difficult to show you some projects because we mostly work on
corporate internal sites.  But for example www.makeawish.be is build on
Ruby on Rails. As well you can see on our vacancies we are looking for a
RoR developer.

On Fri, Aug 28, 2015 at 4:33 PM, Christophe Philemotte <
notifications@github.com> wrote:

> @bertgoossens https://github.com/bertgoossens after having browsed your
> website, it wasn't clear if you do ruby or not (I should have checked
> before merging). Could you confirm it? Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brug-be/rubyshops/pull/19#issuecomment-135789448.

## 

Met vriendelijke groeten | Sincères salutations | Mit freundlichen Grüßen |
With kind regardsTell me how you feel about this email:[image: score 1]
http://digiti.likelyhq.com/score/it?user_id=7&value=1[image: score 2]
http://digiti.likelyhq.com/score/it?user_id=7&value=2[image: score 3]
http://digiti.likelyhq.com/score/it?user_id=7&value=3[image: score 4]
http://digiti.likelyhq.com/score/it?user_id=7&value=4[image: digiti]
http://www.digiti.be

_Bert Goossens_
Developer

Diamantstraat 8
B-2200 Herentals
https://www.google.com/maps/place/Digiti/@51.1588233,4.8061665,17z/data=!3m1!4b1!4m2!3m1!1s0x47c15536663cb1f7:0x77bd1e5b0e7b402b?hl=nl-NL

T: +32 14 75 25 75 <003214752575>

[image: Twitter] https://twitter.com/bertgoossens14

_www.digiti.be_ http://www.digiti.be

Please consider your _environmental responsibility_:
Before printing this e-mail, ask yourself whether you need a hard copy.

This message is strictly confidential and is intended for the stated
addressee(s) only. If you are not the intended addressee, any disclosure or
copying of the contents of this e-mail or any action taken (or not taken)
in reliance on it is unauthorized.If you are not the addressee, please
inform the sender immediately.

**Comment by toch** [comment]
@Reprazent thanks :+1:! It's indeed a good indication :).
@bertgoossens thanks a lot for the confirmation!

We are all good then :).

**Pull request merged**
