### PR TITLE
Add HipByte

### PR DESCRIPTION
**Pull request by JuanitoFatas**

### CODE REVIEW

**Comment by toch** [comment]
Thanks @JuanitoFatas!

As RubyMotion is already mentioned, don't you think it's a duplicate?

**Comment by JuanitoFatas** [comment]
> As RubyMotion is already mentioned, don't you think it's a duplicate?

http://hipbyte.com/ [they launched new business](https://twitter.com/RubyMotion/status/742721157087002624), not just for RubyMotion anymore :)

**Comment by toch** [comment]
you're right, forgot that new one! :clap:

**Comment by JuanitoFatas** [comment]
yay 🍻

**Pull request merged**
